name: Build and Create Release

on:
  push:
    branches:
      - 'master'

jobs:
  pre-release:
    name: 'pre-release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Build & test'
        run: |
          npm ci
          tsc --skipLibCheck
          node ./dist/index.js

      - uses: montudor/action-zip@v1
        with:
          args: cd build && zip -qq -r cookieclicker-cn.zip CookieClickerCNMod

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: '最新版本'
          files: |
            build/cookieclicker-cn.zip
