name: Build and Create Release

on:
  push:
    branches:
      - 'master'

jobs:
  pre-release:
    name: 'pre-release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Download latest current.json'
        run: |
          mkdir -p ./build
          wget https://github.com/TeeworldsCN/CookieClickerCN/releases/download/latest/current.json -O ./build/current.json

      - name: 'Test & Build'
        run: |
          npm ci
          tsc --skipLibCheck
          node ./dist/index.js
          cp ./resources/static/* ./build/CookieClickerCNMod/
          cp ./resources/static_chs/* ./build/CookieClickerCNMod/
          cp ./resources/static/* ./build/CookieClickerTCNMod/
          cp ./resources/static_cht/* ./build/CookieClickerTCNMod/

      - name: Archive Release (CHS)
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'build'
          filename: 'cookieclicker-chs.zip'
          path: 'CookieClickerCNMod'

      - name: Archive Release (CHT)
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'build'
          filename: 'cookieclicker-cht.zip'
          path: 'CookieClickerTCNMod'

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: '最新版本'
          files: |
            build/cookieclicker-chs.zip
            build/cookieclicker-cht.zip
            build/current.json
