name: Verify build

on:
  pull_request:
    branches:
      - 'master'
jobs:
  verify:
    name: 'verify'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Test & Build'
        run: |
          npm ci
          tsc --skipLibCheck
          node ./dist/index.js
          cp ./resources/static/* ./build/CookieClickerCNMod/

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'build'
          filename: 'cookieclicker-cn.zip'
          path: 'CookieClickerCNMod'

      - uses: actions/upload-artifact@v2
        with:
          name: cookieclicker-cn.zip
          path: build/
