name: Verify build

on:
  pull_request:
    branches:
      - 'master'

jobs:
  verify:
    name: 'verify'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Test & Build'
        run: |
          npm ci
          tsc --skipLibCheck
          node ./dist/index.js
          cp ./resources/static/* ./build/CookieClickerCNMod/

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          directory: 'build'
          filename: 'cookieclicker-cn.zip'
          path: 'CookieClickerCNMod'

      - uses: actions/upload-artifact@v4
        with:
          name: cookieclicker-cn.zip
          path: build/
